name = "Gazelle"
# badges = ["travis"]
authority="cpan:KAZEBURO"
module_maker="ModuleBuild"

[build]
build_class = "builder::MyBuilder"

[FileGatherer]
exclude_match = ['^lib/Plack/Handler/picohttpparser/picotest']
